export const context = 'learning'

export const SET_KEYWORD = 'LEARNING/SET_KEYWORD'
export const FETCH_KEYWORDS = 'LEARNING/FETCH_KEYWORDS'
export const FETCH_KEYWORDS_SUCCEEDED = 'LEARNING/FETCH_KEYWORDS_SUCCEEDED'
export const FETCH_KEYWORDS_FAILED = 'LEARNING/FETCH_KEYWORDS_FAILED'
