export const SET_USER_NAME = 'App/SET_USER_NAME'
export const context = 'global'
export const SET_DOWNLOAD_DATA = 'App/SET_DOWNLOAD_DATA'
export const LOG_IN_USER = 'App/LOG_IN_USER'
export const CHECK_LOG_IN = 'App/CHECK_LOG_IN'
export const LOG_OUT_USER = 'App/LOG_OUT_USER'
